import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import morgan from 'morgan';
import dotenv from 'dotenv';
import path from 'path';
import routes from './routes.js';
import { pool } from './db.js';

dotenv.config();
const app=express();
app.set('trust proxy',1);
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use(cors({origin:process.env.CLIENT_ORIGIN||'http://localhost:5173',credentials:true}));
app.use(cookieParser());
app.use('/api/payment/webhook', express.raw({type:'application/json',limit:'1mb'}));
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:true,limit:'1mb'}));
app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:'draft-8',legacyHeaders:false}));
app.use(morgan('dev'));
app.use('/uploads',express.static(path.resolve(process.env.UPLOAD_DIR||'../uploads'),{index:false}));
app.get('/',(_,res)=>res.json({service:'curve-api',status:'running',health:'/api/health',frontend:process.env.CLIENT_ORIGIN||'http://localhost:5173'}));
app.get('/api/health',async(_,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,service:'curve-api',database:'mysql'})}catch{res.status(503).json({ok:false,database:'unavailable'})}});
app.use('/api',routes);
app.use((err,_req,res,_next)=>{console.error(err);const status=err.status||((err.code==='ER_DUP_ENTRY')?409:500);res.status(status).json({message:err.name==='ZodError'?err.issues.map(x=>x.message).join(', '):(err.message||'Internal server error')});});
const port=Number(process.env.PORT||5000);
app.listen(port,()=>console.log(`CURVE API running on http://localhost:${port}`));
